comecando-primefaces/src/main/java/com/lm/erp/model/Empresa.java
package com.lm.erp.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;

import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.br.CNPJ;

@Entity
public class Empresa implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	private Long id;

	@NotEmpty
	@Column(name = "nome_fantasia", nullable = false, length = 80)
	private String nomeFantasia;

	@NotEmpty
	@Column(name = "razao_social", nullable = false, length = 120)
	private String razaoSocial;

	@NotEmpty
	@CNPJ
	@Column(nullable = false, length = 18)
	private String cnpj;

	@NotNull
	@Past
	@Temporal(TemporalType.DATE)
	@Column(name = "data_fundacao")
	private Date dataFundacao;

	@NotNull
	@Enumerated(EnumType.STRING)
	private TipoEmpresa tipo;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNomeFantasia() {
		return nomeFantasia;
	}

	public void setNomeFantasia(String nomeFantasia) {
		this.nomeFantasia = nomeFantasia;
	}

	public String getRazaoSocial() {
		return razaoSocial;
	}

	public void setRazaoSocial(String razaoSocial) {
		this.razaoSocial = razaoSocial;
	}

	public String getCnpj() {
		return cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	public Date getDataFundacao() {
		return dataFundacao;
	}

	public void setDataFundacao(Date dataFundacao) {
		this.dataFundacao = dataFundacao;
	}

	public TipoEmpresa getTipo() {
		return tipo;
	}

	public void setTipo(TipoEmpresa tipo) {
		this.tipo = tipo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Empresa other = (Empresa) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

comecando-primefaces/src/main/java/com/lm/erp/model/TipoEmpresa.java
package com.lm.erp.model;

public enum TipoEmpresa {

	MEI("Microempreendedor Individual"),
	EIRELI("Empresa Individual de Responsabilidade Limitada"),
	LTDA("Sociedade Limitada"),
	SA("Sociedade Anônima");

	private String descricao;

	TipoEmpresa(String descricao) {
		this.descricao = descricao;
	}

	public String getDescricao() {
		return descricao;
	}

}

comecando-primefaces/src/main/java/com/lm/erp/controller/GestaoEmpresasBean.java
package com.lm.erp.controller;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lm.erp.model.Empresa;
import com.lm.erp.model.TipoEmpresa;
import com.lm.erp.repository.Empresas;
import com.lm.erp.service.CadastroEmpresaService;
import com.lm.erp.util.FacesMessages;

@Named
@ViewScoped
public class GestaoEmpresasBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private Empresas empresas;

	@Inject
	private CadastroEmpresaService cadastroEmpresa;

	@Inject
	private FacesMessages messages;

	private List<Empresa> todasEmpresas;
	private Empresa empresaEdicao = new Empresa();
	private Empresa empresaSelecionada;

	public void prepararNovoCadastro() {
		empresaEdicao = new Empresa();
	}

	public void salvar() {
		cadastroEmpresa.salvar(empresaEdicao);
		consultar();
		messages.info("Empresa salva com sucesso!");
		RequestContext.getCurrentInstance().update(Arrays.asList("frm:msgs", "frm:empresas-table"));
	}

	public void excluir() {
		cadastroEmpresa.excluir(empresaSelecionada);
		empresaSelecionada = null;
		consultar();
		messages.info("Empresa excluida com sucesso!");
	}

	public void consultar() {
		todasEmpresas = empresas.todas();
	}

	public List<Empresa> getTodasEmpresas() {
		return todasEmpresas;
	}

	public TipoEmpresa[] getTiposEmpresas() {
		return TipoEmpresa.values();
	}

	public Empresa getEmpresaEdicao() {
		return empresaEdicao;
	}

	public void setEmpresaEdicao(Empresa empresaEdicao) {
		this.empresaEdicao = empresaEdicao;
	}

	public Empresa getEmpresaSelecionada() {
		return empresaSelecionada;
	}

	public void setEmpresaSelecionada(Empresa empresaSelecionada) {
		this.empresaSelecionada = empresaSelecionada;
	}

}

comecando-primefaces/src/main/webapp/GestaoEmpresas.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/templates/Layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	<ui:define name="corpo">
	
		<f:metadata>
			<f:viewAction action="#{gestaoEmpresasBean.consultar}" />
		</f:metadata>
		
		<h1>Cadastro de Empresas</h1>
	
		<h:form id="frm">
		
			<p:messages id="msgs"/>
		
			<p:toolbar id="toolbar">
				<f:facet name="left">
					<p:commandLink action="#{gestaoEmpresasBean.prepararNovoCadastro}" title="Novo cadastro" disabled="#{gestaoEmpresasBean.empresaSelecionada != null}"
					process="@this" update="empresa-dialog" oncomplete="PF('edicaoEmpresaDialog').show()" >
						<h:graphicImage library="lm/img/icones" name="novo.png" width="35" />
						<p:resetInput target="empresa-dialog"/>
					</p:commandLink>			
					<p:commandLink title="Editar"
						process="@this" update="empresa-dialog"
						oncomplete="PF('edicaoEmpresaDialog').show()"
						disabled="#{gestaoEmpresasBean.empresaSelecionada == null}">
							<h:graphicImage library="lm/img/icones" name="editar.png" width="35" />
							<p:resetInput target="empresa-dialog"/>
							<f:setPropertyActionListener value="#{gestaoEmpresasBean.empresaSelecionada}" 
								target="#{gestaoEmpresasBean.empresaEdicao}"/>
						</p:commandLink>
					
					<p:commandLink title="Excluir"
						process="@this" update="empresas-table msgs toolbar"
						action="#{gestaoEmpresasBean.excluir}"
						disabled="#{gestaoEmpresasBean.empresaSelecionada == null}" >
							<h:graphicImage library="lm/img/icones" name="delete.png" width="35" />
							<p:confirm icon="ui-icon-alert" header="Confirmação de exclusão"
							message="Tem certeza que deseja excluir a empresa?" />
						</p:commandLink>
					
				</f:facet>
				
				<f:facet name="right">
					<p:commandLink title="Exportar para XLS" ajax="false" immediate="true" >
						<h:graphicImage library="lm/img/icones" name="xls.png" width="35" />
						<p:dataExporter type="xls" target="empresas-table" fileName="empresas"/>
					</p:commandLink>
						
					<p:commandLink title="Exporat para pdf" ajax="false" immediate="true">
						<h:graphicImage library="lm/img/icones" name="pdf.png" width="35" />
	   					<p:dataExporter type="pdf" target="empresas-table" fileName="empresas" />
					</p:commandLink>
				</f:facet>
			</p:toolbar>
		
			<p:dataTable value="#{gestaoEmpresasBean.todasEmpresas}" var="empresa"
				emptyMessage="Nenhuma empresa cadastrada." rows="10" paginator="true"
				paginatorPosition="bottom" reflow="true"
				style="margin-top: 10px;" id="empresas-table"
				selection="#{gestaoEmpresasBean.empresaSelecionada}" selectionMode="single" rowKey="#{empresa.id}">
				
				<p:ajax event="rowSelect" update=":frm:toolbar" />
				<p:ajax event="rowUnselect" update=":frm:toolbar" />

				<p:column headerText="Razão social" sortBy="#{empresa.razaoSocial}">
					<h:outputText value="#{empresa.razaoSocial}" />
				</p:column>
				<p:column headerText="Nome fantasia" width="250">
					<h:outputText value="#{empresa.nomeFantasia}" />
				</p:column>
				<p:column headerText="CNPJ" width="160">
					<h:outputText value="#{empresa.cnpj}" />
				</p:column>
			</p:dataTable>
			
			<p:dialog header="Nova empresa" id="empresa-dialog" 
				widgetVar="edicaoEmpresaDialog" resizable="false" modal="true" closeOnEscape="true">
				
				<p:messages id="msgs-dialog" />
				<p:defaultCommand target="salvar-button" scope="painel-dialog"/>
				
				<h:panelGrid columns="2" id="painel-dialog">
					<p:outputLabel value="Nome fantasia" for="nome-fantasia"/>
					<p:inputText id="nome-fantasia" size="60" maxlength="80"
					 value="#{gestaoEmpresasBean.empresaEdicao.nomeFantasia}"/>
					
					<p:outputLabel value="Razão social" for="razao-social"/>
					<p:inputText id="razao-social" size="60" maxlength="120"
					value="#{gestaoEmpresasBean.empresaEdicao.razaoSocial}" />
					
					<p:outputLabel value="CNPJ" for="cnpj"/>
					<p:inputMask id="cnpj" size="18" maxlength="18"
					value="#{gestaoEmpresasBean.empresaEdicao.cnpj}" 
					mask="99.999.999/9999-99" />
					
					<p:outputLabel value="Data de fundação" for="data-fundacao"/>
					<p:calendar id="data-fundacao" size="10"
					value="#{gestaoEmpresasBean.empresaEdicao.dataFundacao}"
					pattern="dd/MM/yyyy" mask="99/99/9999" locale="pt" />
					
					<p:outputLabel value="Tipo" for="tipo"/>
					<p:selectOneMenu id="tipo" value="#{gestaoEmpresasBean.empresaEdicao.tipo}">
						<f:selectItem itemLabel="Selecione"/>
						<f:selectItems value="#{gestaoEmpresasBean.tiposEmpresas}" var="tipo"
						itemLabel="#{tipo.descricao}" itemValue="#{tipo}" />
					</p:selectOneMenu>
					
					<p:outputLabel/>
					<p:commandButton value="Salvar" id="salvar-button"
					action="#{gestaoEmpresasBean.salvar}" 
					process="empresa-dialog" update="msgs-dialog painel-dialog"
					oncomplete="if(!args.validationFailed) PF('edicaoEmpresaDialog').hide()" />
				</h:panelGrid>
			</p:dialog>
			
		</h:form>
		
	</ui:define>
</ui:composition>

comecando-primefaces/src/main/webapp/WEB-INF/templates/Layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<meta charset="UTF-8" />
	<h:outputStylesheet library="lm/css" name="estilo.css" />
</h:head>
<h:body>

	<header>
		<h:graphicImage library="lm/img" name="logo.jpg" />
	</header>

	<div id="conteudo">
		<ui:insert name="corpo" />
	</div>

	<footer> 	&#169; 2016 - Todos os direitos reservados. </footer>

	<h:form>
		<p:confirmDialog global="true">
			<p:commandButton value="Não" type="button"
				styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
				
				<p:commandButton value="Sim" type="button"
				styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
		</p:confirmDialog>
	</h:form>

</h:body>
<script type="text/javascript">
	PrimeFaces.locales['pt'] = {
		closeText : 'Fechar',
		prevText : 'Anterior',
		nextText : 'Próximo',
		currentText : 'Começo',
		monthNames : [ 'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio',
				'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro',
				'Dezembro' ],
		monthNamesShort : [ 'Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul',
				'Ago', 'Set', 'Out', 'Nov', 'Dez' ],
		dayNames : [ 'Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta',
				'Sexta', 'Sábado' ],
		dayNamesShort : [ 'Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb' ],
		dayNamesMin : [ 'D', 'S', 'T', 'Q', 'Q', 'S', 'S' ],
		weekHeader : 'Semana',
		firstDay : 0,
		isRTL : false,
		showMonthAfterYear : false,
		yearSuffix : '',
		timeOnlyTitle : 'Só Horas',
		timeText : 'Tempo',
		hourText : 'Hora',
		minuteText : 'Minuto',
		secondText : 'Segundo',
		ampm : false,
		month : 'Mês',
		week : 'Semana',
		day : 'Dia',
		allDayText : 'Todo o Dia'
	};
</script>

</html>

comecando-primefaces/src/main/webapp/teste.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<meta charset="UTF-8" />
</h:head>
<h:body>
	<h:form>
		<p:panel header="Cadastro de cliente">
			<h:panelGrid columns="2">
				<p:outputLabel value="Nome" />
				<p:inputText />
				<p:outputLabel value="CPF" />
				<p:inputMask mask="999.999.999-99" />
				<p:outputLabel value="Data de nascimento" />
				<p:calendar pattern="dd/MM/yyyy" mask="99/99/9999" />
				<p:outputLabel />
				<p:commandButton value="Salvar" />
			</h:panelGrid>
		</p:panel>
	</h:form>
</h:body>
</html>